Be 002 insert new project mutation
WildCodeSchool/2109-wns-remote3-jahbaf-back pull request #12
Opened 2021-11-23 19:12 UTC by Julien-Brcht-Rndlt

2021-11-23 22:03 UTC, FlorentAlamachere commented on src/exceptions/projects/index.ts
> +export * from './projects.exceptions';
Je ne pense pas que tu aies besoin de cet index.ts, les codes ne sont utilisés que dans le fichier d'exception situé dans le meme folder, pas besoin de les exporter globalement du coup.
Et comme dans ton dossier projets tu n'exportes finalement que le fichier .exceptions.ts, tu n'as pas forcement besoin de créer un fichier index juste pour un seul fichier, bien que ce soit une question de point de vue.

2021-11-23 22:03 UTC, FlorentAlamachere commented on src/exceptions/index.ts
> +export * from './projects/projects.exceptions';
Si jamais tu laisses le fichier exceptions/projects/index.ts, ton export ici peut devenir : 
export * from './projects'

2021-11-23 22:03 UTC, FlorentAlamachere commented on src/exceptions/projects/projects.codes.ts
> +export const MISSING_MANDATORY_FIELD = 2001;
Tu peux eventuellement utiliser un enum ici, pas obligatoire, mais c'est une idée

2021-11-23 22:03 UTC, FlorentAlamachere commented on src/exceptions/projects/projects.exceptions.ts
> +import { MISSING_MANDATORY_FIELD } from 'src/exceptions/projects/projects.codes';
Tes codes sont dans le meme dossier, ton import devrais etre quelque chose comme : 
import ... from './projects.codes';

2021-11-23 22:03 UTC, FlorentAlamachere commented on src/repositories/projects/projects.repository.ts
> +export const findProjectByName = async (
Tu peux supprimer cette fonction, tu ne l'utilises pas ailleurs, et il y aura des noms identiques (même si on reflechiras a une strategie de differenciation lorsque l'on ajoutera le crowdfunding) donc l'implem n'est pas bonne.
Si on veut garder cette fonction on ne doit pas dans ce cas utiliser findFirst, mais findAll, et eventuellement ne pas faire forcement de recherche sur le nom complet, mais sur une partie du nom. Par exemple commencer a chercher un projet une fois les 3 premieres lettres tapées.

2021-11-23 22:03 UTC, FlorentAlamachere commented on src/services/projects/projects.service.ts
> +    const { name } = projectInput;
La destructuration n'est pas forcement utile, parce que tu ne reutilise pas vraiment name.
Un check tel que if(!projectInput.name){ } est suffisant, le service est suffisamment simple pour que cela reste comprehensible.
Voire meme : 
!projectInput.name && throw new MissingMandatoryFieldException();

Question de goûts ^^

2021-11-23 22:08 UTC, FlorentAlamachere requested changes
Detail supplementaire, il me semble que tu as oublié d'ajouter les infos au fichier de documentation.
docs/api.json

2021-11-24 09:48 UTC, Julien-Brcht-Rndlt commented on src/exceptions/projects/index.ts
> +export * from './projects.exceptions';
done

2021-11-24 09:49 UTC, Julien-Brcht-Rndlt commented on src/repositories/projects/projects.repository.ts
> +export const findProjectByName = async (
removed

2021-11-24 09:54 UTC, Julien-Brcht-Rndlt commented on src/exceptions/projects/projects.codes.ts
> +export const MISSING_MANDATORY_FIELD = 2001;
changed with an enum a discussed

2021-11-24 10:22 UTC, FlorentAlamachere commented on docs/api.json
> +        "returns": "{ createProject: Project }",
Ton objet de retour ne ressemble pas à ça ? 
data : {
    createProject: {
        id: blabla,
        ...
    }
}

Mais plutot à ça non ?

data : {
    project: {
        id: blabla,
        ...
    }
}

Dans ce cas
"returns": "{ project: Project }"

2021-11-24 10:27 UTC, FlorentAlamachere commented on src/resolvers/projects/createProject.mutation.ts
> +    return await createProjectService(projectInput);
const project = await createProjectService(projectInput)
return { project }

2021-11-24 10:28 UTC, Julien-Brcht-Rndlt commented on docs/api.json
> +        "returns": "{ createProject: Project }",
c'est bien la structure 
data : {
  createProject: {
  id: blabla,
  ...
  }
}
qui est retouné par défaut via apollo server en prenant le nom du resolver

2021-11-24 11:33 UTC, FlorentAlamachere approved these changes

2021-11-24 11:33 UTC, merged